group=io.ballerina.lib
version=1.1.3-SNAPSHOT

checkstylePluginVersion=10.12.0
spotbugsPluginVersion=6.5.1
shadowJarPluginVersion=9.6.1
downloadPluginVersion=5.4.0
releasePluginVersion=3.1.0
githubSpotbugsVersion=5.0.14
githubJohnrengelmanShadowVersion=8.1.1
underCouchDownloadVersion=5.4.0
researchgateReleaseVersion=2.8.0
redshiftDriverVersion=2.2.9
ballerinaGradlePluginVersion=4.0.0
ballerinaLangVersion=2201.11.0
