[package]
distribution = "2201.11.0"
org = "ballerinax"
name = "aws.redshift.driver"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Data Warehouse", "Cost/Paid", "Columnar Storage", "driver", "vendor/aws"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.redshift.driver"

[[platform.java21.dependency]]
groupId = "com.amazon.redshift"
artifactId = "redshift-jdbc42"
version = "@aws.redshift.driver.version@"
path = "./lib/redshift-jdbc42-@aws.redshift.driver.version@.jar"
